class InputEvent:
    @property
    def kind(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def button(self) -> str: ...
    @property
    def row(self) -> int: ...
    @property
    def column(self) -> int: ...
    @property
    def ctrl(self) -> bool: ...
    @property
    def alt(self) -> bool: ...
    @property
    def shift(self) -> bool: ...

class EventReader:
    def __init__(self) -> None: ...
    def __enter__(self) -> EventReader: ...
    def __exit__(self, *args: object) -> bool: ...
    def enable_mouse_capture(self) -> None: ...
    def disable_mouse_capture(self) -> None: ...
    def poll_event(self, timeout_ms: int = ...) -> InputEvent | None: ...
    @property
    def mouse_capture_enabled(self) -> bool: ...

def emergency_restore() -> None: ...

__version__: str
